spring.config.import=optional:file:.env[.properties]

spring.application.name=Wellbeing


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.default_schema=wellbeing
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_ACCESS_EXPIRATION}


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

razor.key.id=${RAZOR_KEY_ID}
razor.key.secret=${RAZOR_KEY_SECRET}

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=${GEMINI_API_URL}

logging.level.org.springframework.boot.context.config=DEBUG

