spring.application.name=Wellbeing


spring.datasource.url=jdbc:postgresql://ep-blue-dew-aouo7rij.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_9Zkioy4HaRIN

spring.jpa.properties.hibernate.default_schema=wellbeing
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=6A576E5A7234753778214125442A472D4B6150645367566B5970337336763979
jwt.expiration=172800000


spring.mail.host=smtp.gmail.com
spring.mail.port=587 
spring.mail.username=thotanishanthnetha222@gmail.com
spring.mail.password=mtygttsfiibhlzqs
spring.mail.properties.mail.smtp.auth=true 
spring.mail.properties.mail.smtp.starttls.enable=true
